import type { ExerciseProgram } from '@/types/exercise'

export const mockPrograms: ExerciseProgram[] = [
  {
    id: 'prog1',
    patientId: 'p1',
    nome: 'Recupero ginocchio dx - Fase 2',
    descrizione: 'Programma di rinforzo e stabilizzazione post-distorsione LCM',
    esercizi: [
      {
        exerciseId: 'ex11',
        serie: 3,
        ripetizioni: 12,
        tempoRecupero: '60s',
        note: 'Non superare i 45° di flessione',
      },
      {
        exerciseId: 'ex12',
        serie: 3,
        ripetizioni: 15,
        tempoRecupero: '45s',
        note: 'Con cavigliera da 1 kg',
      },
      {
        exerciseId: 'ex9',
        serie: 3,
        ripetizioni: 15,
        tempoRecupero: '45s',
        note: '',
      },
      {
        exerciseId: 'ex16',
        serie: 3,
        ripetizioni: 1,
        tempoRecupero: '60s',
        note: 'Mantenere 30 secondi per serie',
      },
    ],
    stato: 'attivo',
    dataInizio: '2026-01-20',
    dataFine: '2026-03-20',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prog2',
    patientId: 'p2',
    nome: 'Cervicalgia - Mobilizzazione e rinforzo',
    descrizione: 'Programma domiciliare per gestione cervicalgia cronica e postura',
    esercizi: [
      {
        exerciseId: 'ex1',
        serie: 2,
        ripetizioni: 10,
        tempoRecupero: '30s',
        note: 'Movimento lento e controllato',
      },
      {
        exerciseId: 'ex2',
        serie: 3,
        ripetizioni: 10,
        tempoRecupero: '30s',
        note: 'Mantenere 10 secondi per ripetizione',
      },
      {
        exerciseId: 'ex7',
        serie: 2,
        ripetizioni: 10,
        tempoRecupero: '30s',
        note: 'Inspirare in estensione, espirare in flessione',
      },
      {
        exerciseId: 'ex17',
        serie: 2,
        ripetizioni: 3,
        tempoRecupero: '30s',
        note: 'Mantenere 30 secondi per ripetizione',
      },
    ],
    stato: 'attivo',
    dataInizio: '2026-02-01',
    dataFine: '2026-04-01',
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'prog3',
    patientId: 'p1',
    nome: 'Recupero ginocchio dx - Fase 1',
    descrizione: 'Programma iniziale post-infortunio: mobilità e controllo dolore',
    esercizi: [
      {
        exerciseId: 'ex12',
        serie: 2,
        ripetizioni: 10,
        tempoRecupero: '60s',
        note: 'Senza cavigliera',
      },
      {
        exerciseId: 'ex9',
        serie: 2,
        ripetizioni: 10,
        tempoRecupero: '45s',
        note: '',
      },
    ],
    stato: 'completato',
    dataInizio: '2025-12-20',
    dataFine: '2026-01-19',
    createdAt: '2025-12-20T10:00:00Z',
  },
  {
    id: 'prog4',
    patientId: 'p2',
    nome: 'Postura - Ergonomia quotidiana',
    descrizione: 'Micro-pause ed esercizi da eseguire alla scrivania',
    esercizi: [
      {
        exerciseId: 'ex2',
        serie: 5,
        ripetizioni: 5,
        tempoRecupero: '10s',
        note: 'Ogni 2 ore durante il lavoro al PC',
      },
      {
        exerciseId: 'ex17',
        serie: 3,
        ripetizioni: 1,
        tempoRecupero: '15s',
        note: 'Mantenere 20 secondi, mattina e sera',
      },
    ],
    stato: 'sospeso',
    dataInizio: '2026-01-15',
    dataFine: '2026-03-15',
    createdAt: '2026-01-15T14:00:00Z',
  },
]
