import type { Patient } from '@/types/patient'

const emptyStileVita = {
  usoAlcool: '',
  fumo: '',
  dieta: '',
  attivitaFisica: '',
  oreSedutoGiorno: null,
  frequenzaAttivitaFisica: '',
  statoCivile: '',
  stressPercepito: '',
  obiettivoTrattamento: '',
}

const emptySportivo = {
  sportPrincipale: '',
  livello: '',
  sportSecondari: '',
  anniPratica: null,
  frequenzaAllenamenti: '',
  oreAllenamenti: null,
  posizioneRuolo: '',
  dateImportanti: '',
  obiettiviFisiciSpecifici: '',
  qualitaSonno: '',
  nutrizioneBase: '',
  dataTargetRitornoSport: null,
  noteCoach: '',
}

const emptyTestFisici = {
  rom: '',
  altezzaSaltoVerticale: '',
  sprintVelocity: '',
  equilibrioSway: '',
  forzaMuscolare: '',
  postura: '',
}

const emptyAnamnesiGenerale = {
  peso: null,
  altezza: null,
  infortuniPregressi: '',
  dataUltimoInfortunio: null,
  limitazioniFunzionali: '',
  patologieCronicheNote: '',
  interventiChirurgici: '',
  farmaciAbituali: '',
  terapieFisicheEseguite: '',
  trattamentiComplementari: '',
  allergieNote: '',
  percezioneCondizione: '',
  gravidanza: '',
  menopausa: '',
}

const emptyAnamnesiSpecifica = {
  motivoTerapia: '',
  sintomi: '',
  localizzazioneDolore: '',
  irradiazioneDolore: '',
  tipologiaDolore: '',
  intensitaDolore: null,
  fattoriAggravanti: '',
  fattoriAllevianti: '',
  esordioProblema: '',
  andamentoTemporale: '',
  limitazioniFunzionali: '',
  diagnosiPregresse: '',
}

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    anagrafica: {
      nome: 'Marco',
      cognome: 'Rossi',
      sesso: 'M',
      dataNascita: '1985-03-15',
      luogoNascita: 'Roma',
      statoNascita: 'Italia',
      codiceFiscale: 'RSSMRC85C15H501Z',
      cartaIdentita: 'CA12345AB',
      indirizzoResidenza: 'Via Roma 42, Roma',
      indirizzoDomicilio: 'Via Roma 42, Roma',
      cap: '00185',
      telefono: '+39 333 1234567',
      email: 'marco.rossi@email.it',
      aslAppartenenza: 'ASL Roma 1',
      medicoCurante: 'Dr. Bianchi',
      tipoAssicurazione: 'SSN',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: { ...emptySportivo, sportPrincipale: 'Calcio', livello: 'Amatoriale' },
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: true,
    createdAt: '2025-11-10T10:00:00Z',
    updatedAt: '2026-01-20T14:30:00Z',
  },
  {
    id: 'p2',
    anagrafica: {
      nome: 'Laura',
      cognome: 'Bianchi',
      sesso: 'F',
      dataNascita: '1992-07-22',
      luogoNascita: 'Milano',
      statoNascita: 'Italia',
      codiceFiscale: 'BNCLRA92L62F205X',
      cartaIdentita: 'CA67890CD',
      indirizzoResidenza: 'Corso Buenos Aires 78, Milano',
      indirizzoDomicilio: 'Corso Buenos Aires 78, Milano',
      cap: '20124',
      telefono: '+39 347 9876543',
      email: 'laura.bianchi@email.it',
      aslAppartenenza: 'ATS Milano',
      medicoCurante: 'Dr.ssa Verdi',
      tipoAssicurazione: 'Privata',
      compagniaAssicurativa: 'UniSalute',
      numeroPolizza: 'US-2024-12345',
    },
    stileVita: emptyStileVita,
    sportivo: emptySportivo,
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: false,
    createdAt: '2025-12-05T09:00:00Z',
    updatedAt: '2026-02-01T11:15:00Z',
  },
  {
    id: 'p3',
    anagrafica: {
      nome: 'Giuseppe',
      cognome: 'Esposito',
      sesso: 'M',
      dataNascita: '1978-11-03',
      luogoNascita: 'Napoli',
      statoNascita: 'Italia',
      codiceFiscale: 'SPSGPP78S03F839Y',
      cartaIdentita: 'CA11223EF',
      indirizzoResidenza: 'Via Toledo 156, Napoli',
      indirizzoDomicilio: 'Via Toledo 156, Napoli',
      cap: '80134',
      telefono: '+39 320 5551234',
      email: 'g.esposito@email.it',
      aslAppartenenza: 'ASL Napoli 1',
      medicoCurante: 'Dr. Ferraro',
      tipoAssicurazione: 'SSN',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: emptySportivo,
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: false,
    createdAt: '2025-10-18T15:45:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'p4',
    anagrafica: {
      nome: 'Chiara',
      cognome: 'Ferrari',
      sesso: 'F',
      dataNascita: '1995-01-28',
      luogoNascita: 'Torino',
      statoNascita: 'Italia',
      codiceFiscale: 'FRRCHR95A68L219P',
      cartaIdentita: 'CA44556GH',
      indirizzoResidenza: 'Via Po 33, Torino',
      indirizzoDomicilio: 'Via Po 33, Torino',
      cap: '10124',
      telefono: '+39 338 7778899',
      email: 'chiara.ferrari@email.it',
      aslAppartenenza: 'ASL TO3',
      medicoCurante: 'Dr.ssa Colombo',
      tipoAssicurazione: 'Mista',
      compagniaAssicurativa: 'Generali',
      numeroPolizza: 'GEN-2025-67890',
    },
    stileVita: emptyStileVita,
    sportivo: { ...emptySportivo, sportPrincipale: 'Tennis', livello: 'Agonistico' },
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: true,
    createdAt: '2026-01-02T08:30:00Z',
    updatedAt: '2026-02-05T16:00:00Z',
  },
  {
    id: 'p5',
    anagrafica: {
      nome: 'Alessandro',
      cognome: 'Conti',
      sesso: 'M',
      dataNascita: '1960-06-10',
      luogoNascita: 'Bologna',
      statoNascita: 'Italia',
      codiceFiscale: 'CNTLSS60H10A944T',
      cartaIdentita: 'CA77889IJ',
      indirizzoResidenza: 'Via Indipendenza 20, Bologna',
      indirizzoDomicilio: 'Via Indipendenza 20, Bologna',
      cap: '40121',
      telefono: '+39 051 4567890',
      email: 'a.conti@email.it',
      aslAppartenenza: 'AUSL Bologna',
      medicoCurante: 'Dr. Moretti',
      tipoAssicurazione: 'SSN',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: emptySportivo,
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: false,
    createdAt: '2025-09-20T12:00:00Z',
    updatedAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'p6',
    anagrafica: {
      nome: 'Sofia',
      cognome: 'Romano',
      sesso: 'F',
      dataNascita: '2001-09-14',
      luogoNascita: 'Firenze',
      statoNascita: 'Italia',
      codiceFiscale: 'RMNSFO01P54D612W',
      cartaIdentita: 'CA99001KL',
      indirizzoResidenza: 'Lungarno Amerigo Vespucci 8, Firenze',
      indirizzoDomicilio: 'Lungarno Amerigo Vespucci 8, Firenze',
      cap: '50123',
      telefono: '+39 392 1112233',
      email: 'sofia.romano@email.it',
      aslAppartenenza: 'USL Toscana Centro',
      medicoCurante: 'Dr.ssa Ricci',
      tipoAssicurazione: 'Nessuna',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: { ...emptySportivo, sportPrincipale: 'Pallavolo', livello: 'Agonistico' },
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: true,
    createdAt: '2026-01-20T14:00:00Z',
    updatedAt: '2026-02-08T09:45:00Z',
  },
]
