import type { Patient } from '@/types/patient'

const emptyStileVita = {
  usoAlcool: '',
  fumo: '',
  dieta: '',
  attivitaFisica: '',
  oreSedutoGiorno: null,
  frequenzaAttivitaFisica: '',
  statoCivile: '',
  stressPercepito: '',
  obiettivoTrattamento: '',
}

const emptySportivo = {
  sportPrincipale: '',
  livello: '',
  sportSecondari: '',
  anniPratica: null,
  frequenzaAllenamenti: '',
  oreAllenamenti: null,
  posizioneRuolo: '',
  dateImportanti: '',
  obiettiviFisiciSpecifici: '',
  qualitaSonno: '',
  nutrizioneBase: '',
  dataTargetRitornoSport: null,
  noteCoach: '',
}

const emptyTestFisici = {
  rom: '',
  altezzaSaltoVerticale: '',
  sprintVelocity: '',
  equilibrioSway: '',
  forzaMuscolare: '',
  postura: '',
}

const emptyAnamnesiGenerale = {
  peso: null,
  altezza: null,
  infortuniPregressi: '',
  dataUltimoInfortunio: null,
  limitazioniFunzionali: '',
  patologieCronicheNote: '',
  interventiChirurgici: '',
  farmaciAbituali: '',
  terapieFisicheEseguite: '',
  trattamentiComplementari: '',
  allergieNote: '',
  percezioneCondizione: '',
  gravidanza: '',
  menopausa: '',
}

const emptyAnamnesiSpecifica = {
  motivoTerapia: '',
  sintomi: '',
  localizzazioneDolore: '',
  irradiazioneDolore: '',
  tipologiaDolore: '',
  intensitaDolore: null,
  fattoriAggravanti: '',
  fattoriAllevianti: '',
  esordioProblema: '',
  andamentoTemporale: '',
  limitazioniFunzionali: '',
  diagnosiPregresse: '',
}

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    anagrafica: {
      nome: 'Marco',
      cognome: 'Rossi',
      sesso: 'M',
      dataNascita: '1985-03-15',
      luogoNascita: 'Roma',
      statoNascita: 'Italia',
      codiceFiscale: 'RSSMRC85C15H501Z',
      cartaIdentita: 'CA12345AB',
      indirizzoResidenza: 'Via Roma 42, Roma',
      indirizzoDomicilio: 'Via Roma 42, Roma',
      cap: '00185',
      telefono: '+39 333 1234567',
      email: 'marco.rossi@email.it',
      aslAppartenenza: 'ASL Roma 1',
      medicoCurante: 'Dr. Bianchi',
      tipoAssicurazione: 'SSN',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: {
      usoAlcool: 'Occasionale',
      fumo: 'No',
      dieta: 'Onnivora',
      attivitaFisica: 'Moderata',
      oreSedutoGiorno: 6,
      frequenzaAttivitaFisica: '3-4 v/sett',
      statoCivile: 'Sposato/a',
      stressPercepito: '4',
      obiettivoTrattamento: 'Tornare a giocare a calcetto senza dolore al ginocchio destro',
    },
    sportivo: {
      sportPrincipale: 'Calcio',
      livello: 'Amatoriale',
      sportSecondari: 'Corsa, Nuoto',
      anniPratica: 20,
      frequenzaAllenamenti: '3-4',
      oreAllenamenti: 6,
      posizioneRuolo: 'Centrocampista',
      dateImportanti: 'Torneo aziendale 15/06',
      obiettiviFisiciSpecifici: 'Recupero completo ginocchio dx, migliorare resistenza',
      qualitaSonno: 'Buona',
      nutrizioneBase: 'Dieta equilibrata, integrazione proteica post-allenamento',
      dataTargetRitornoSport: '2026-04-01',
      noteCoach: 'Evitare cambi di direzione bruschi per le prime 2 settimane',
    },
    testFisici: {
      rom: 'Ginocchio dx: flessione 120°, estensione completa. Spalla: nella norma.',
      altezzaSaltoVerticale: '35',
      sprintVelocity: '4.2',
      equilibrioSway: 'Lieve instabilità monopodalica dx',
      forzaMuscolare: 'Quadricipite dx: 4/5 MRC, sx: 5/5 MRC',
      postura: 'Lieve anteriorizzazione del bacino, spalle nella norma',
    },
    anamnesiGenerale: {
      peso: 78,
      altezza: 180,
      infortuniPregressi: 'Distorsione ginocchio dx (2023), stiramento polpaccio sx (2021)',
      dataUltimoInfortunio: '2025-12-10',
      limitazioniFunzionali: 'Difficoltà nella corsa prolungata e nei cambi di direzione',
      patologieCronicheNote: 'Nessuna',
      interventiChirurgici: 'Nessuno',
      farmaciAbituali: 'Nessuno',
      terapieFisicheEseguite: 'Fisioterapia post-distorsione (10 sedute, 2023)',
      trattamentiComplementari: 'Massaggio sportivo occasionale',
      allergieNote: 'Nessuna',
      percezioneCondizione: 'Discreta',
      gravidanza: '',
      menopausa: '',
    },
    anamnesiSpecifica: {
      motivoTerapia: 'Dolore al ginocchio destro persistente dopo distorsione in partita',
      sintomi: 'Dolore localizzato al compartimento mediale, gonfiore intermittente',
      localizzazioneDolore: 'Ginocchio destro, compartimento mediale',
      irradiazioneDolore: 'Nessuna irradiazione',
      tipologiaDolore: 'Sordo',
      intensitaDolore: 5,
      fattoriAggravanti: 'Corsa, salire le scale, stare in piedi a lungo',
      fattoriAllevianti: 'Riposo, ghiaccio, elevazione',
      esordioProblema: 'Post-traumatico',
      andamentoTemporale: 'Miglioramento',
      limitazioniFunzionali: 'Non riesce a correre oltre 20 minuti, difficoltà a scendere le scale',
      diagnosiPregresse: 'Distorsione LCM grado I-II (RM dicembre 2025)',
    },
    refertiMedici: [
      {
        id: 'r1',
        tipoEsame: 'Risonanza Magnetica',
        dataReferto: '2025-12-15',
        medicoRefertante: 'Dr. Martini',
        descrizione:
          'RM ginocchio dx: lieve distensione del LCM con edema perilegamentoso. Menischi integri. Cartilagine articolare nella norma. Minimo versamento articolare.',
        immagineUrl: '',
        raccomandazioniTerapeutiche: 'Fisioterapia conservativa, evitare attività sportiva per 4-6 settimane',
      },
      {
        id: 'r2',
        tipoEsame: 'Radiografia',
        dataReferto: '2025-12-11',
        medicoRefertante: 'Dr.ssa Colombo',
        descrizione:
          'Rx ginocchio dx in 2 proiezioni: non evidenti lesioni ossee. Rapporti articolari conservati. Lieve tumefazione dei tessuti molli periarticolari.',
        immagineUrl: '',
        raccomandazioniTerapeutiche: 'Si consiglia approfondimento con RM',
      },
    ],
    isSportivo: true,
    createdAt: '2025-11-10T10:00:00Z',
    updatedAt: '2026-01-20T14:30:00Z',
  },
  {
    id: 'p2',
    anagrafica: {
      nome: 'Laura',
      cognome: 'Bianchi',
      sesso: 'F',
      dataNascita: '1992-07-22',
      luogoNascita: 'Milano',
      statoNascita: 'Italia',
      codiceFiscale: 'BNCLRA92L62F205X',
      cartaIdentita: 'CA67890CD',
      indirizzoResidenza: 'Corso Buenos Aires 78, Milano',
      indirizzoDomicilio: 'Corso Buenos Aires 78, Milano',
      cap: '20124',
      telefono: '+39 347 9876543',
      email: 'laura.bianchi@email.it',
      aslAppartenenza: 'ATS Milano',
      medicoCurante: 'Dr.ssa Verdi',
      tipoAssicurazione: 'Privata',
      compagniaAssicurativa: 'UniSalute',
      numeroPolizza: 'US-2024-12345',
    },
    stileVita: {
      usoAlcool: 'Nessuno',
      fumo: 'No',
      dieta: 'Vegetariana',
      attivitaFisica: 'Leggera',
      oreSedutoGiorno: 8,
      frequenzaAttivitaFisica: '1-2 v/sett',
      statoCivile: 'Convivente',
      stressPercepito: '7',
      obiettivoTrattamento: 'Ridurre dolore cervicale e migliorare postura da lavoro al PC',
    },
    sportivo: emptySportivo,
    testFisici: emptyTestFisici,
    anamnesiGenerale: {
      peso: 58,
      altezza: 165,
      infortuniPregressi: 'Nessuno',
      dataUltimoInfortunio: null,
      limitazioniFunzionali: 'Rigidità cervicale, cefalea tensiva frequente',
      patologieCronicheNote: 'Emicrania con aura',
      interventiChirurgici: 'Nessuno',
      farmaciAbituali: 'Sumatriptan al bisogno',
      terapieFisicheEseguite: 'Nessuna precedente',
      trattamentiComplementari: 'Yoga 1 volta a settimana',
      allergieNote: 'Penicillina',
      percezioneCondizione: 'Scarsa',
      gravidanza: 'No',
      menopausa: 'No',
    },
    anamnesiSpecifica: {
      motivoTerapia: 'Cervicalgia cronica con cefalea tensiva associata',
      sintomi: 'Dolore cervicale bilaterale, rigidità mattutina, cefalea tensiva 3-4 volte/settimana',
      localizzazioneDolore: 'Rachide cervicale, trapezi bilaterali',
      irradiazioneDolore: 'Dal collo alla regione occipitale e temporo-parietale',
      tipologiaDolore: 'Sordo',
      intensitaDolore: 6,
      fattoriAggravanti: 'Lavoro al PC prolungato, stress, posizioni statiche',
      fattoriAllevianti: 'Calore, stretching, riposo',
      esordioProblema: 'Graduale',
      andamentoTemporale: 'Stabile',
      limitazioniFunzionali: 'Difficoltà nella rotazione cervicale, ridotta concentrazione',
      diagnosiPregresse: 'Cervicalgia cronica, discopatia C5-C6 (RM 2024)',
    },
    refertiMedici: [
      {
        id: 'r3',
        tipoEsame: 'Risonanza Magnetica',
        dataReferto: '2024-09-20',
        medicoRefertante: 'Dr. Neri',
        descrizione:
          'RM rachide cervicale: protrusione discale C5-C6 mediana-paramediana dx senza compressione radicolare. Rettilineizzazione della lordosi cervicale.',
        immagineUrl: '',
        raccomandazioniTerapeutiche: 'Fisioterapia, valutazione posturale, ergonomia postazione lavoro',
      },
    ],
    isSportivo: false,
    createdAt: '2025-12-05T09:00:00Z',
    updatedAt: '2026-02-01T11:15:00Z',
  },
  {
    id: 'p3',
    anagrafica: {
      nome: 'Giuseppe',
      cognome: 'Esposito',
      sesso: 'M',
      dataNascita: '1978-11-03',
      luogoNascita: 'Napoli',
      statoNascita: 'Italia',
      codiceFiscale: 'SPSGPP78S03F839Y',
      cartaIdentita: 'CA11223EF',
      indirizzoResidenza: 'Via Toledo 156, Napoli',
      indirizzoDomicilio: 'Via Toledo 156, Napoli',
      cap: '80134',
      telefono: '+39 320 5551234',
      email: 'g.esposito@email.it',
      aslAppartenenza: 'ASL Napoli 1',
      medicoCurante: 'Dr. Ferraro',
      tipoAssicurazione: 'SSN',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: emptySportivo,
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: false,
    createdAt: '2025-10-18T15:45:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'p4',
    anagrafica: {
      nome: 'Chiara',
      cognome: 'Ferrari',
      sesso: 'F',
      dataNascita: '1995-01-28',
      luogoNascita: 'Torino',
      statoNascita: 'Italia',
      codiceFiscale: 'FRRCHR95A68L219P',
      cartaIdentita: 'CA44556GH',
      indirizzoResidenza: 'Via Po 33, Torino',
      indirizzoDomicilio: 'Via Po 33, Torino',
      cap: '10124',
      telefono: '+39 338 7778899',
      email: 'chiara.ferrari@email.it',
      aslAppartenenza: 'ASL TO3',
      medicoCurante: 'Dr.ssa Colombo',
      tipoAssicurazione: 'Mista',
      compagniaAssicurativa: 'Generali',
      numeroPolizza: 'GEN-2025-67890',
    },
    stileVita: emptyStileVita,
    sportivo: { ...emptySportivo, sportPrincipale: 'Tennis', livello: 'Agonistico' },
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: true,
    createdAt: '2026-01-02T08:30:00Z',
    updatedAt: '2026-02-05T16:00:00Z',
  },
  {
    id: 'p5',
    anagrafica: {
      nome: 'Alessandro',
      cognome: 'Conti',
      sesso: 'M',
      dataNascita: '1960-06-10',
      luogoNascita: 'Bologna',
      statoNascita: 'Italia',
      codiceFiscale: 'CNTLSS60H10A944T',
      cartaIdentita: 'CA77889IJ',
      indirizzoResidenza: 'Via Indipendenza 20, Bologna',
      indirizzoDomicilio: 'Via Indipendenza 20, Bologna',
      cap: '40121',
      telefono: '+39 051 4567890',
      email: 'a.conti@email.it',
      aslAppartenenza: 'AUSL Bologna',
      medicoCurante: 'Dr. Moretti',
      tipoAssicurazione: 'SSN',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: emptySportivo,
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: false,
    createdAt: '2025-09-20T12:00:00Z',
    updatedAt: '2026-01-15T10:30:00Z',
  },
  {
    id: 'p6',
    anagrafica: {
      nome: 'Sofia',
      cognome: 'Romano',
      sesso: 'F',
      dataNascita: '2001-09-14',
      luogoNascita: 'Firenze',
      statoNascita: 'Italia',
      codiceFiscale: 'RMNSFO01P54D612W',
      cartaIdentita: 'CA99001KL',
      indirizzoResidenza: 'Lungarno Amerigo Vespucci 8, Firenze',
      indirizzoDomicilio: 'Lungarno Amerigo Vespucci 8, Firenze',
      cap: '50123',
      telefono: '+39 392 1112233',
      email: 'sofia.romano@email.it',
      aslAppartenenza: 'USL Toscana Centro',
      medicoCurante: 'Dr.ssa Ricci',
      tipoAssicurazione: 'Nessuna',
      compagniaAssicurativa: '',
      numeroPolizza: '',
    },
    stileVita: emptyStileVita,
    sportivo: { ...emptySportivo, sportPrincipale: 'Pallavolo', livello: 'Agonistico' },
    testFisici: emptyTestFisici,
    anamnesiGenerale: emptyAnamnesiGenerale,
    anamnesiSpecifica: emptyAnamnesiSpecifica,
    refertiMedici: [],
    isSportivo: true,
    createdAt: '2026-01-20T14:00:00Z',
    updatedAt: '2026-02-08T09:45:00Z',
  },
]
